# -*- coding: utf-8 -*-
"""volume_of_sphere

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QvdHQJKdTANM0IoBah_pB8a0QQK2L4a-
"""

def compute_volume_of_sphere(radius):
	pi = 3.14
	area = pi * radius * radius * radius * (4/3)
	return volume

radius1 = 30
area1 = compute_volume_of_sphere(radius1)
print(f"The volume of sphere with radius {radius1} is: {area1}")

radius2 = 40
area2 = compute_volume_of_sphere(radius2)
print(f"The volume of sphere with radius {radius2} is: {area2}")